datasources:
  # Configure Postgres with the env vars from the add-on <1>
  postgres:
    url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRESQL_ADDON_USER}
    password: ${POSTGRESQL_ADDON_PASSWORD}
kestra:
  server:
    basicAuth:
      enabled: true
      username: ${BASIC_AUTH_USERNAME}
      password: ${BASIC_AUTH_PASSWORD}
  queue:
    type: postgres
  repository:
    type: postgres
  storage:
    type: s3
    s3:
      endpoint: https://${CELLAR_ADDON_HOST}
      accessKey: ${CELLAR_ADDON_KEY_ID}
      secretKey:  ${CELLAR_ADDON_KEY_SECRET}
      region: US
      bucket: kestra-internal-storage
  tasks:
    tmpDir:
      path: "/tmp/kestra-wd/tmp"
micronaut:
  server:
    port: 8080
  url: https://${CC_DOMAIN}