datasources:
  postgres:
    url: jdbc:postgresql://postgres:5432/kestra
    driverClassName: org.postgresql.Driver
    username: kestra
    password: k3str4
kestra:
  server:
    basicAuth:
      enabled: false
      username: "admin@kestra.io" # it must be a valid email address
      password: kestra
  queue:
    type: postgres
  repository:
    type: postgres
  storage:
    type: s3
  tasks:
    tmpDir:
      path: "/tmp/kestra-wd/tmp"
  micronaut:
  server:
    port: 8080
  url: "http://localhost:8080/"