datasources:
  # Configure Postgres with the env vars from the add-on <1>
  postgres:
    url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRESQL_ADDON_USER}
    password: ${POSTGRESQL_ADDON_PASSWORD}
kestra:
  server:
    basicAuth:
      enabled: true
      username: ${BASIC_AUTH_USERNAME}
      password: ${BASIC_AUTH_PASSWORD}
  queue:
    type: postgres
  repository:
    type: postgres
  storage:
    type: minio
    minio:
      endpoint: https://${CELLAR_ADDON_HOST}
      port: 80
      accessKey: ${CELLAR_ADDON_KEY_ID}
      secretKey:  ${CELLAR_ADDON_KEY_SECRET}
      region: US
      bucket: ${BUCKET_NAME}
  tasks:
    tmpDir:
      path: "/tmp/kestra-wd/tmp"
  # As the Docker engine is not accessible, configure globally the Process runner for all plugins <5>
  plugins:
    defaults:
      - type: io.kestra.plugin.scripts
        values:
          taskRunner:
            type: io.kestra.plugin.core.runner.Process      
micronaut:
  server:
    port: 8080
  url: https://${CC_DOMAIN}