#!/usr/bin/env bash
#MISE description="Build the app"
pip install s3cmd
cat > ~/.s3cfg << EOF
[default]
access_key = $CELLAR_ADDON_KEY_ID
secret_key = $CELLAR_ADDON_KEY_SECRET
host_base = $CELLAR_ADDON_HOST
host_bucket = $CELLAR_ADDON_HOST
use_https = True
EOF
# Create the bucket
s3cmd mb s3://$BUCKET_NAME

mkdir -p $APP_HOME/kestra-install
wget -nv https://api.kestra.io/v1/versions/download -O $APP_HOME/kestra-install/kestra.zip
unzip $APP_HOME/kestra-install/kestra.zip -d $APP_HOME/kestra-install
rm -f $APP_HOME/kestra-install/kestra.zip

# The zip contains a single file, an executable jar without jar extension.
# We need to find this file and store it in the KESTRA_DIR variable.
# The problem is that the file name depends on the version, e.g. kestra-0.23.8
for file in $(ls $APP_HOME/kestra-install/*); do
    if [[ -f $file ]]; then
        KESTRA_EXEC="$file"
        break
    fi
done
ln -sf $KESTRA_EXEC $APP_HOME/kestra

export KESTRA_PLUGINS_PATH=$APP_HOME/kestra-install/plugins
mkdir -p $KESTRA_PLUGINS_PATH

# Install S3 storage plugin
/opt/openjdk-bin-23.0.2_p7/bin/java -jar $APP_HOME/kestra plugins install io.kestra.storage:storage-minio:LATEST
